# Generated by Django 5.2.1 on 2026-01-12 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_profile_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AddField(
            model_name='profile',
            name='_notes',
            field=models.TextField(blank=True, db_column='notes', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='_password',
            field=models.TextField(blank=True, db_column='password', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='_username',
            field=models.TextField(blank=True, db_column='username', null=True),
        ),
    ]
