# Generated by Django 5.2.1 on 2026-01-12 09:55

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_profile_notes_remove_profile_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='_email',
            field=models.TextField(blank=True, db_column='email', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='_recovery_codes',
            field=models.TextField(blank=True, db_column='recovery_codes', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='document',
            field=models.FileField(blank=True, help_text='Upload document (PDF, images, etc.) - Max 10MB', null=True, upload_to='profile_documents/', validators=[api.models.validate_file_size]),
        ),
    ]
