# Generated by Django 5.2.1 on 2026-01-13 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_security_pin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetotp',
            options={'verbose_name': 'Password Reset OTP', 'verbose_name_plural': 'Password Reset OTPs'},
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passwordresetotp',
            name='max_attempts',
            field=models.IntegerField(default=5),
        ),
    ]
