# Generated by Django 5.2.1 on 2026-01-13 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_loginrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginrecord',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
