# Generated by Django 5.2.1 on 2026-01-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_encryption_salt_to_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_breached',
            field=models.BooleanField(default=False, help_text='Whether this password has been found in known data breaches'),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_breach_check_date',
            field=models.DateTimeField(blank=True, help_text='Last time this password was checked against HIBP', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='last_password_update',
            field=models.DateTimeField(blank=True, help_text='Last time the password was changed', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='password_strength',
            field=models.IntegerField(default=0, help_text='zxcvbn strength score (0-4)'),
        ),
    ]
