# Generated by Django 5.2.1 on 2026-01-15 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_profile_password_hash'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_token', models.CharField(db_index=True, help_text='URL-safe unique token', max_length=64, unique=True)),
                ('encrypted_payload', models.TextField(help_text='AES-256-GCM encrypted JSON payload')),
                ('expires_at', models.DateTimeField(help_text='When this link expires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_at', models.DateTimeField(blank=True, help_text='When the link was accessed (for burn-on-read)', null=True)),
                ('is_accessed', models.BooleanField(db_index=True, default=False, help_text='Whether this link has been accessed')),
                ('created_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('viewer_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('viewer_user_agent', models.TextField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to='api.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Shared Link',
                'verbose_name_plural': 'Shared Links',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['share_token', 'is_accessed'], name='api_sharedl_share_t_31511a_idx'), models.Index(fields=['expires_at'], name='api_sharedl_expires_45d5bc_idx')],
            },
        ),
    ]
