# Generated by Django 5.2.1 on 2026-01-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_sharedlink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SharedLink',
        ),
    ]
