# Generated by Django 5.2.10 on 2026-01-17 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_loginrecord_is_duress_alter_loginrecord_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='website_link',
            field=models.URLField(blank=True, help_text='Organization website URL', null=True),
        ),
    ]
