# Generated by Django 5.2.10 on 2026-01-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_website_link_to_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuratedOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='Organization name', max_length=200)),
                ('domain', models.CharField(db_index=True, help_text='Primary domain (e.g., google.com)', max_length=255, unique=True)),
                ('logo_url', models.URLField(blank=True, help_text='External logo URL or local file path', null=True)),
                ('is_verified', models.BooleanField(default=True, help_text='Verified/trusted organization')),
                ('priority', models.IntegerField(default=0, help_text='Sort priority (higher = shown first)')),
                ('website_link', models.URLField(blank=True, help_text='Official website URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curated Organization',
                'verbose_name_plural': 'Curated Organizations',
                'ordering': ['-priority', 'name'],
                'indexes': [models.Index(fields=['name'], name='api_curated_name_dab8ab_idx'), models.Index(fields=['domain'], name='api_curated_domain_c8513d_idx')],
            },
        ),
    ]
