# Generated by Django 5.2.10 on 2026-01-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_curated_organization_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='curatedorganization',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Upload logo image from local system', null=True, upload_to='curated_org_logos/'),
        ),
        migrations.AddField(
            model_name='curatedorganization',
            name='logo_svg',
            field=models.TextField(blank=True, help_text='SVG code (paste raw SVG)', null=True),
        ),
        migrations.AddField(
            model_name='curatedorganization',
            name='logo_type',
            field=models.CharField(choices=[('url', 'External URL'), ('upload', 'Upload Image'), ('svg', 'SVG Code')], default='url', help_text='How the logo is provided', max_length=10),
        ),
        migrations.AlterField(
            model_name='curatedorganization',
            name='logo_url',
            field=models.URLField(blank=True, help_text='External logo URL (e.g., from CDN)', null=True),
        ),
    ]
