# Generated by Django 5.2.10 on 2026-01-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_usersession'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
