# Generated by Django 5.2.10 on 2026-01-20 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_delete_usersession'),
        ('authtoken', '0004_alter_tokenproxy_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(help_text='Raw User-Agent string')),
                ('device_type', models.CharField(default='desktop', help_text='mobile, desktop, tablet', max_length=20)),
                ('browser', models.CharField(blank=True, help_text='e.g., Chrome 120', max_length=100)),
                ('os', models.CharField(blank=True, help_text='e.g., Windows 11', max_length=100)),
                ('location', models.CharField(blank=True, help_text='e.g., Mumbai, India', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(auto_now=True)),
                ('token', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='authtoken.token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Session',
                'verbose_name_plural': 'User Sessions',
                'ordering': ['-last_active'],
            },
        ),
    ]
