# Generated by Django 5.2.10 on 2026-01-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_multitoken_alter_usersession_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='country_code',
            field=models.CharField(blank=True, help_text='ISO country code, e.g., IN', max_length=10),
        ),
        migrations.AddField(
            model_name='usersession',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this session is active'),
        ),
    ]
