# Generated by Django 5.2.10 on 2026-01-21 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_add_session_active_and_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='password_hash',
        ),
    ]
