# Generated by Django 5.2.10 on 2026-01-21 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_password_hash_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_hash',
            field=models.CharField(blank=True, help_text='SHA-256 hash of password for uniqueness checking (not for authentication)', max_length=64, null=True),
        ),
    ]
