# Generated by Django 5.2.10 on 2026-01-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_zero_knowledge_vault'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='duress_auth_hash',
            field=models.CharField(blank=True, help_text='Auth hash for duress login verification (derived from duress password, not reversible)', max_length=128, null=True),
        ),
    ]
