# Generated by Django 5.2.10 on 2026-01-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_loginrecord_password_attempted'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='card_brand',
            field=models.CharField(blank=True, help_text='Card brand (Visa, Mastercard, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_cvv_encrypted',
            field=models.TextField(blank=True, help_text='AES-256-GCM encrypted CVV', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_cvv_iv',
            field=models.CharField(blank=True, help_text='Initialization vector for CVV', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_design',
            field=models.CharField(blank=True, default='sbi', help_text='Card UI design theme', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_expiry_encrypted',
            field=models.TextField(blank=True, help_text='AES-256-GCM encrypted card expiry (MM/YY)', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_expiry_iv',
            field=models.CharField(blank=True, help_text='Initialization vector for card expiry', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_holder_name_encrypted',
            field=models.TextField(blank=True, help_text='AES-256-GCM encrypted card holder name', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_holder_name_iv',
            field=models.CharField(blank=True, help_text='Initialization vector for card holder name', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_number_encrypted',
            field=models.TextField(blank=True, help_text='AES-256-GCM encrypted card number', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_number_iv',
            field=models.CharField(blank=True, help_text='Initialization vector for card number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_pin_encrypted',
            field=models.TextField(blank=True, help_text='AES-256-GCM encrypted PIN', null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='card_pin_iv',
            field=models.CharField(blank=True, help_text='Initialization vector for PIN', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='credential_type',
            field=models.CharField(choices=[('LOGIN', 'Login Credential'), ('CARD', 'Credit/Debit Card'), ('NOTE', 'Secure Note')], default='LOGIN', help_text='Type of credential stored in this profile', max_length=10),
        ),
    ]
