# Generated by Django 5.2.10 on 2026-01-23 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_add_credit_card_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='card_brand',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='card_cvv_encrypted',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='card_cvv_iv',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='card_design',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='card_expiry_encrypted',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='card_expiry_iv',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='card_holder_name_encrypted',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='card_holder_name_iv',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='card_number_encrypted',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='card_number_iv',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='card_pin_encrypted',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='card_pin_iv',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='credential_type',
        ),
    ]
