# Generated by Django 5.2.10 on 2026-01-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_profile_card_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='When the profile was moved to trash (null = not deleted)', null=True),
        ),
    ]
