# Generated by Django 5.2.10 on 2026-01-26 09:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_add_deleted_at_to_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CanaryTrap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique high-entropy token for the trap URL', unique=True)),
                ('label', models.CharField(help_text="Human-readable label, e.g., 'Fake AWS Key', 'Corporate VPN'", max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this trap is meant to look like', null=True)),
                ('trap_type', models.CharField(choices=[('web_login', 'Web Login URL'), ('api_key', 'API Key'), ('webhook', 'Webhook URL')], default='web_login', help_text='Type of trap credential', max_length=20)),
                ('vault_profile_id', models.IntegerField(blank=True, help_text='ID of the auto-created vault profile containing this trap', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the trap is active (will trigger alerts)')),
                ('triggered_count', models.PositiveIntegerField(default=0, help_text='Number of times the trap has been triggered')),
                ('last_triggered_at', models.DateTimeField(blank=True, help_text='When the trap was last triggered', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the trap was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the trap was last updated')),
                ('user', models.ForeignKey(help_text='Owner of the canary trap', on_delete=django.db.models.deletion.CASCADE, related_name='canary_traps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Canary Trap',
                'verbose_name_plural': 'Canary Traps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CanaryTrapTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the accessor', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='User-Agent header from the request')),
                ('referer', models.URLField(blank=True, default='', help_text='Referer header (where the request came from)', max_length=2048)),
                ('country', models.CharField(blank=True, default='', help_text='Country from IP geolocation', max_length=100)),
                ('isp', models.CharField(blank=True, default='', help_text='ISP from IP geolocation', max_length=200)),
                ('additional_data', models.JSONField(blank=True, default=dict, help_text='Additional data captured during trigger')),
                ('alert_sent', models.BooleanField(default=False, help_text='Whether an alert email was sent')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, help_text='When the trigger occurred')),
                ('trap', models.ForeignKey(help_text='The trap that was triggered', on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='api.canarytrap')),
            ],
            options={
                'verbose_name': 'Canary Trap Trigger',
                'verbose_name_plural': 'Canary Trap Triggers',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
