# Generated by Django 5.2.1 on 2026-01-12 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, help_text='Profile title or name', max_length=200, null=True),
        ),
    ]
