# Generated by Django 5.2.10 on 2026-01-12 14:58

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_remove_profile_notes_remove_profile_password_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="document",
            field=models.FileField(
                blank=True,
                help_text="Upload document (PDF, images, etc.) - Max 10MB",
                null=True,
                upload_to="profile_documents/",
                validators=[api.models.validate_file_size],
            ),
        ),
    ]
