# Generated by Django 5.2.10 on 2026-01-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_profile_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="_email",
            field=models.TextField(blank=True, db_column="email", null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="_recovery_codes",
            field=models.TextField(blank=True, db_column="recovery_codes", null=True),
        ),
    ]
