# Generated by Django 5.2.10 on 2026-01-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_profile__email_profile__recovery_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="security_pin",
            field=models.CharField(
                blank=True,
                help_text="4-digit security PIN for accessing organizations",
                max_length=4,
                null=True,
            ),
        ),
    ]
