# Generated by Django 5.2.10 on 2026-01-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_loginrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="loginrecord",
            name="timezone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
