# Generated by Django 5.2.10 on 2026-01-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_loginrecord_timezone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="_email",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="_notes",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="_password",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="_recovery_codes",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="_username",
        ),
        migrations.AddField(
            model_name="profile",
            name="email_encrypted",
            field=models.TextField(
                blank=True, help_text="AES-256-GCM encrypted email", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="email_iv",
            field=models.CharField(
                blank=True,
                help_text="Initialization vector for email",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="notes_encrypted",
            field=models.TextField(
                blank=True, help_text="AES-256-GCM encrypted notes", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="notes_iv",
            field=models.CharField(
                blank=True,
                help_text="Initialization vector for notes",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="password_encrypted",
            field=models.TextField(
                blank=True, help_text="AES-256-GCM encrypted password", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="password_iv",
            field=models.CharField(
                blank=True,
                help_text="Initialization vector for password",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="recovery_codes_encrypted",
            field=models.TextField(
                blank=True, help_text="AES-256-GCM encrypted recovery codes", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="recovery_codes_iv",
            field=models.CharField(
                blank=True,
                help_text="Initialization vector for recovery codes",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="username_encrypted",
            field=models.TextField(
                blank=True, help_text="AES-256-GCM encrypted username", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="username_iv",
            field=models.CharField(
                blank=True,
                help_text="Initialization vector for username",
                max_length=100,
                null=True,
            ),
        ),
    ]
