# Generated by Django 5.2.10 on 2026-01-14 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_remove_profile__email_remove_profile__notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="encryption_salt",
            field=models.CharField(
                blank=True,
                help_text="Salt for deriving client-side encryption key",
                max_length=255,
                null=True,
            ),
        ),
    ]
