# Generated by Django 5.2.10 on 2026-01-15 23:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_profile_password_hash"),
    ]

    operations = [
        migrations.CreateModel(
            name="SharedSecret",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("encrypted_blob", models.TextField()),
                ("salt", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("view_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_secrets",
                        to="api.profile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shared Secret",
                "verbose_name_plural": "Shared Secrets",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["expires_at"], name="api_shareds_expires_5af49b_idx"
                    ),
                    models.Index(
                        fields=["profile", "created_at"],
                        name="api_shareds_profile_a13fe1_idx",
                    ),
                ],
            },
        ),
    ]
