# Generated by Django 5.2.10 on 2026-01-16 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_sharedsecret"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="loginrecord",
            name="is_duress",
            field=models.BooleanField(
                default=False, help_text="True if this was a duress password login"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="duress_password_hash",
            field=models.CharField(
                blank=True,
                help_text="Hashed duress password for ghost vault access",
                max_length=128,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="panic_shortcut",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of keys for panic shortcut, e.g., ['Alt', 'X']",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="sos_email",
            field=models.EmailField(
                blank=True,
                help_text="Email to notify when duress password is used",
                max_length=254,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="loginrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("failed", "Failed"),
                    ("duress", "Duress"),
                ],
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="DuressSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token_key",
                    models.CharField(
                        help_text="The auth token key from rest_framework.authtoken",
                        max_length=40,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="duress_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Duress Session",
                "verbose_name_plural": "Duress Sessions",
                "ordering": ["-created_at"],
            },
        ),
    ]
